title: Cam's Coding Journey
author: Cam Utz
email: dragon8029@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Follow me as I document the up's and downs of becoming an web developer. 

# social links
twitter_username: @Dragon8029
github_username:  Dragon8029

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
